# Dockerfile para el frontend
# Utiliza una imagen de Nginx para servir archivos estáticos
FROM nginx:alpine

# Copia los archivos estáticos al directorio de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80