services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7500:5000"
    volumes:
      - imagenes_data:/app/imagenes.db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  imagenes_data:
 